---
#
# Ansible managed
#
repository:
  description: Update cache for yum and apt package managers.
  homepage: https://robertdebock.nl/
  topics: updatepackagecache, security, ansible, molecule, tox, playbook
